name: tugas3_tpm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.4
  google_maps_flutter: ^2.5.0
  permission_handler: ^11.3.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  shared_preferences: ^2.0.15
  
flutter:
  uses-material-design: true
  assets:
  - assets/images/person1.jpg
  - assets/images/youtube.png
  - assets/images/twitter.jpg
  - assets/images/google.png
  - assets/images/facebook.png
