name: tugas3_tpm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.0.15
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/person1.jpg
  - assets/images/google.png
  - assets/images/youtube.png
  - assets/images/facebook.png
  - assets/images/twitter.jpg
